#!/usr/bin/env bash

set -eo pipefail

rm -rf /tmp/release
mkdir -p /tmp/release
cp bin/dict /tmp/release
VERSION=$(cat resources/VERSION)

pushd /tmp/release

## release binary as zip archive

APP_ARCH=${APP_ARCH:-amd64}

zip "dict-$VERSION-$APP_PLATFORM-$APP_ARCH.zip" dict

rm dict

popd

bb release-artifact --file "/tmp/release/dict-$VERSION-$APP_PLATFORM-$APP_ARCH.zip"
