
a a -> b: first one {link: hilo}
 c-> d: {near: top};a : {3d: true};# comm
aws.link: hi
aws: you {
style.fill: red
a -> b
test: |md
  # I am markdown!
  ## I'm a smaller heading
  - list point 1
  - point 2
  |
 }
 super --\
  -> long